version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - gis_1ban_02_network
    volumes:
    - gis_1ban_02_static:/data/static/
    - gis_1ban_02media:/data/media/
    - home/kyeongseojeon/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80

  django:
    image: gis_1ban_02_django:4
    networks:
      - gis_1ban_02_network
    volumes:
    - gis_1ban_02_static:/home/gis_1ban_02/staticfiles/
    - gis_1ban_02_media:/home/gis_1ban_02/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_1ban_02_network
    volumes:
    - gis_mariadb:/var/lib/mysql
    environment:
      MARIADB_USER: django
      MARIADB_DATABASE: django
      MARIADB_PASSWORD: password1234
      MARIADB_ROOT_PASSWORD: password1234

networks:
  gis_1ban_02_network:

volumes:
  gis_1ban_02_static:
  gis_1ban_02_media:
  gis_mariadb:

