# Generated by Django 3.2.5 on 2021-09-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0004_article_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
